### ISSUE TITLE
Auth issues?

### ISSUE THREAD

**Issue by CognitiveCodes** [weaigc/gpt-web#4]
Hello! Everything was working nicely until last couple days...
 throw new Error('Error login.');
              ^
Error: Error login.
    at Auth.partFive (C:\Users\Altreo.pl\AppData\Roaming\npm\node_modules\gpt-web\dist\auth.js:155:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ChatGPTWeb.chat (C:\Users\Altreo.pl\AppData\Roaming\npm\node_modules\gpt-web\dist\index.js:20:36)
    at async C:\Users\Altreo.pl\AppData\Roaming\npm\node_modules\gpt-web\dist\server.js:42:25

My account works...

**Comment by weaigc** [comment]
@CognitiveCodes 
Auth logic depends on the service of fakeopen.com, which has a certain probability of problems. You can check https://status.fakeopen.com/ to see service status.
