### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by shanshu1015** [weaigc/gpt-web#8]
GPT: /home/kp090412/.nvm/versions/node/v18.20.2/lib/node_modules/gpt-web/dist/auth2.js:71
            throw new Error(resp.statusText);
                  ^

Error: Internal Server Error
    at Auth.getToken (/home/kp090412/.nvm/versions/node/v18.20.2/lib/node_modules/gpt-web/dist/auth2.js:71:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ChatGPTWeb.init (/home/kp090412/.nvm/versions/node/v18.20.2/lib/node_modules/gpt-web/dist/index.js:20:36)
    at async ChatGPTWeb.chat (/home/kp090412/.nvm/versions/node/v18.20.2/lib/node_modules/gpt-web/dist/index.js:26:9)
    at async cli (/home/kp090412/.nvm/versions/node/v18.20.2/lib/node_modules/gpt-web/dist/bin/cli.js:29:26)

**Comment by ZYWNB666** [comment]
me too
